data:
    dataset: "ImageNet"
    image_size: 64
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 32
    subset_1k: True
    out_of_dist: False

model:
    in_channels: 3
    model_channels: 192
    out_channels: 3
    num_res_blocks: 3
    attention_resolutions: [32, 16, 8]
    dropout: 0.0
    channel_mult: [1, 2, 3, 4]
    use_fp16: true
    num_heads: 4
    num_head_channels: 64
    num_heads_upsample: -1
    use_scale_shift_norm: true
    resblock_updown: true
    use_new_attention_order: false
    class_cond: true
    num_classes: 1000


diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 1
    T_sampling: 4